-- MySQL Script generated by MySQL Workbench
-- Wed May  4 20:48:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gest_parque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gest_parque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gest_parque` DEFAULT CHARACTER SET utf8 ;
USE `gest_parque` ;

-- -----------------------------------------------------
-- Table `gest_parque`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`perfil` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_perfil` INT NOT NULL,
  `nome` VARCHAR(155) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `senha` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_au_user_au_role_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_au_user_au_role`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `gest_parque`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`estacionamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`estacionamento` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`estacionamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `ordem` INT NOT NULL DEFAULT 0,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`marca` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`modelo` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_marca` INT NOT NULL,
  `nome` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cr_model_cr_brand1_idx` (`id_marca` ASC),
  CONSTRAINT `fk_cr_model_cr_brand1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `gest_parque`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `id_modelo` INT NOT NULL,
  `cor` VARCHAR(150) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cr_veicle_cr_model1_idx` (`id_modelo` ASC),
  UNIQUE INDEX `code_UNIQUE` (`matricula` ASC),
  INDEX `fk_cr_car_au_user1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_cr_veicle_cr_model1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `gest_parque`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cr_car_au_user1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gest_parque`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`promocao` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`promocao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(3,2) NOT NULL,
  `data_inicio` Date NOT NULL,
  `data_fim` Date NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`ticket` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estacionamento` INT NOT NULL,
  `id_veiculo` INT NOT NULL,
  `data_entrada` DATETIME NOT NULL,
  `data_saida` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  `id_promocao` INT NULL,
  `montante` DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_op_slot_has_car_pk_slot1_idx` (`id_estacionamento` ASC),
  INDEX `fk_op_slot_has_car_cr_car1_idx` (`id_veiculo` ASC),
  INDEX `fk_op_ticket_au_user1_idx` (`id_usuario` ASC),
  INDEX `fk_op_ticket_pm_promotions1_idx` (`id_promocao` ASC),
  CONSTRAINT `fk_op_slot_has_car_pk_slot1`
    FOREIGN KEY (`id_estacionamento`)
    REFERENCES `gest_parque`.`estacionamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_op_slot_has_car_cr_car1`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `gest_parque`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_op_ticket_au_user1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gest_parque`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_op_ticket_pm_promotions1`
    FOREIGN KEY (`id_promocao`)
    REFERENCES `gest_parque`.`promocao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gest_parque`.`preco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gest_parque`.`preco` ;

CREATE TABLE IF NOT EXISTS `gest_parque`.`preco` (
  `dia_semana` INT NOT NULL,
  `primeira_hora` DECIMAL(12,2) NOT NULL,
  `segunda_hora` DECIMAL(12,2) NOT NULL,
  `restante` DECIMAL(12,2) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gest_parque`.`perfil`
-- -----------------------------------------------------
START TRANSACTION;
USE `gest_parque`;
INSERT INTO `gest_parque`.`perfil` (`id`, `nome`) VALUES (1, 'Administrador');
INSERT INTO `gest_parque`.`perfil` (`id`, `nome`) VALUES (2, 'Funcionario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gest_parque`.`marca`
-- -----------------------------------------------------
START TRANSACTION;
USE `gest_parque`;
INSERT INTO `gest_parque`.`marca` (`id`, `nome`) VALUES (1, 'Toyota');
INSERT INTO `gest_parque`.`marca` (`id`, `nome`) VALUES (2, 'Huyndai');
INSERT INTO `gest_parque`.`marca` (`id`, `nome`) VALUES (3, 'Kia');

COMMIT;

